GroupPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('vote/', include('voting.urls', namespace='voting')),
    path('accounts/', include('django.contrib.auth.urls')),  # Для login/logout
 ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Відображення профілю групи (головна сторінка)
    path('', views.GroupProfileView.as_view(), name='group_profile'),
    # Відображення профілю користувача
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    # Оновлення профілю користувача
    path('profile/edit/', views.UserProfileUpdateView.as_view(), name='user_profile_edit'),
    # Реєстрація
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

voting/urls.py
from django.urls import path
from voting import views

app_name = 'voting'

urlpatterns = [
    path("", views.vote_list, name="vote-list"),
    path("votes/<int:pk>/", views.VoteDetailView.as_view(), name="vote-detail"),
    path("votes/create/", views.VoteCreateView.as_view(), name="vote-create"),
    path("vote/edit/<int:pk>", views.EditYourVoteView.as_view(), name="edit-vote")
]

voting/models.py
from django.db import models

from django.contrib.auth.models import User


class Vote(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_votes")

    def __str__(self):
        return self.title


class VoteOption(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE, related_name="options")
    text = models.CharField(max_length=255)
    vote_count = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.text} ({self.vote.title})"


class UserVote(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE, related_name="user_votes")
    option = models.ForeignKey(VoteOption, on_delete=models.CASCADE, related_name="user_votes")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="votes")
    voted_at = models.DateTimeField(auto_now=True)

voting/forms.py
from voting.models import Vote,VoteOption
from django import forms
from django.forms import inlineformset_factory


class VoteForm(forms.ModelForm):
    class Meta():
        model = Vote
        fields = ['title','description',]
        widgets = {
            'title':forms.TextInput(),
            'description':forms.Textarea()
        }

vote_option_set = inlineformset_factory(Vote,VoteOption,fields=['text'],extra=3,can_delete=False,widgets={'text':forms.TextInput})


class VoteOptionSet(vote_option_set):
    def clean(self):
        super().clean()
        
        field_forms = []

        if self.is_valid():
            for form in self.forms:
                if form.cleaned_data.get('text'):
                    field_forms.append(form) 

            if len(field_forms) < 2:
                raise forms.ValidationError('потрiбно мiнiмум два варiанта')
       

voting/views.py
from django.shortcuts import render,redirect,get_object_or_404
from voting.models import Vote, VoteOption, UserVote
from django.views.generic import DetailView,CreateView,View
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.urls import reverse_lazy
from voting.forms import VoteForm,VoteOptionSet

def vote_list(request):
    votes = Vote.objects.all().order_by("-created_at")
    return render(request, "Voting/vote_list.html", {"votes": votes})


class VoteDetailView(DetailView):
    model = Vote
    template_name = 'Voting/vote_detail.html'
    context_object_name = 'vote'



class VoteCreateView(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Vote
    template_name = 'Voting/vote_create.html'
    success_url = redirect ('voting:vote-list')
    form_class = VoteForm
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['form_set'] = VoteOptionSet(self.request.POST,instance=self.object)
        else:
             context['form_set'] = VoteOptionSet(instance=self.object)
        return context     
         
    def form_valid(self,form):
        context = self.get_context_data()
        form_set = context['form_set']
        if form_set.is_valid():
            form.instance.created_by = self.request.user
            self.object = form.save()
            form_set.instance = self.object
            form_set.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def test_func(self):
        return self.request.user.profile.role == 'admin'


class EditYourVoteView(LoginRequiredMixin,View):
    def post(self,request,pk):
        vote = get_object_or_404(Vote,pk=pk)
        option_id = request.POST.get('option')
        option = get_object_or_404(VoteOption,pk=option_id,vote=vote)
        uservote,exists = UserVote.objects.get_or_create(vote=vote,defaults={'option': option},user=request.user)
        if exists == True:
            option.vote_count += 1 
            option.save()
        else:
            if uservote.option != option:
                uservote.option.vote_count -= 1
                uservote.option.save()
                option.vote_count += 1            
                option.save()
                uservote.option = option
                uservote.save() 
        return redirect ('voting:vote-detail',pk=vote.pk)

templates/Voting/vote_create.html
{% extends 'base.html' %}
{% block content %}
<h1>Створити голосованя</h1>
<form method="post">
    {% csrf_token %}
    <p>title: {{ form.title }}</p>
    <p>description: {{ form.description }}</p>
    <p>choices:</p>
    {% for choices in form_set %}
    <p>{{ choices.text }}</p>
    {% endfor %}
    <button type="submit">создати</button>
</form>
{% endblock %}

templates/Voting/vote_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ vote.title }}</h1>
<p>{{ vote.description }}</p>
<p>Created at:  {{ vote.created_at }}</p>
<p>created_by:  {{ vote.created_by }}</p>
{% if user.is_authenticated %}
<h2>Проголосувати</h2>
<form method="post" action="{% url 'voting:edit-vote' vote.pk %}">
    {% csrf_token %}
    {% for option in vote.options.all %}
    <p><input type="radio" name="option" value="{{ option.id }}" required>{{ option.text }}</input></p>
    {% endfor %}
    <button type="submit">vote</button>
</form>
<h3> результати </h3>
<ul>
    {% for option in vote.options.all %}
    <li> {{ option.text }}: {{ option.vote_count }} голуciв </li>
    {% endfor %}
</ul>
{% else %}
<p>plese <a href="{% url 'login' %}">login</a> to vote</p>
{% endif %}
{% endblock %}

templates/Voting/vote_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Список голосований</h1>
    <ul>
      {% for vote in votes %}
        <li><a href="{% url 'voting:vote-detail' vote.pk %}">{{ vote.title }}</a></li>
      {% endfor %}
    </ul>
    <a href="{% url 'voting:vote-create' %}">створити Голосування</a>
{% endblock %}